import type { Metadata } from 'next'
import './globals.css'
import { inter } from './fonts'
import TanstackProvider from '@/providers/TanstackProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <TanstackProvider>
                    {children}
                </TanstackProvider>
            </body>
        </html>
    )
}
